spring:
  profiles:
    active: ${name:test}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  tomcat:
    threads:
      max: 200
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,beans


