spring:
  profiles:
    active: ${name:test}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
#  tomcat:
#    accept-count: 1
#    max-connections: 250
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches,beans


